test: added test point

diff --git a/fastapi-sonarqube-demo/.github/workflows/sonar.yml b/fastapi-sonarqube-demo/.github/workflows/sonar.yml
--- a/fastapi-sonarqube-demo/.github/workflows/sonar.yml
+++ b/fastapi-sonarqube-demo/.github/workflows/sonar.yml
@@ -8,6 +8,15 @@ on:
 
 jobs:
   build:
+  - name: Debug coverage.xml
+    run: |
+      echo "✅ Listing current folder content"
+      ls -l
+      echo "✅ Searching for coverage.xml recursively"
+      find . -name "coverage.xml"
+      echo "✅ Display coverage.xml"
+      cat coverage.xml || echo "❌ coverage.xml not found"
+
     name: SonarCloud Scan
     runs-on: ubuntu-latest
 
